base_image: null
bundled_packages_dir: packages
data_dir: data
description: TODO
environment_variables: {}
external_package_dirs: []
input_type: Any
live_reload: false
model_class_filename: model.py
model_class_name: Model
model_framework: custom
model_metadata:
  avatar_url: https://cdn.baseten.co/production/static/explore/falcon-avatar.png
  cover_image_url: https://cdn.baseten.co/production/static/explore/falcon-cover.png
  tags:
  - audio-generation
  example:
    prompts:
      - "happy rock"
      - "energetic EDM"
      - "sad jazz"
    duration: 8
model_module_dir: model
model_name: MusicGen medium
model_type: custom
python_version: py39
requirements:
- torch>=2
- audiocraft
resources:
  cpu: "3"
  memory: 14Gi
  use_gpu: true
  accelerator: A10G
secrets: {}
spec_version: '2.0'
system_packages:
- ffmpeg
